### ISSUE TITLE
Chrome OS is showing up as Safari

### ISSUE THREAD

**Issue by bradbirnbaum** [shenoudab/active_device#1]
Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US) AppleWebKit/532.0 (KHTML, like Gecko) Chrome/3.0.195.38 Safari/532.0

calling agent_name with a browser with this URL returns Safari when it is Chrome

**Comment by shenoudab** [comment]
Thanks for sharing that case with us.
that will be handled by the next update.

**Comment by shenoudab** [comment]
Hi Brad, 

  Merry Christmas and Happy New year 2010 ...

kindly, i'd like to notify for the new update of ActiveDevice with handling for Chrome Browser.

for any comments please don't hesitate to send me.
