### ISSUE TITLE
Opera Mini Simulator not being detected as mobile device

### ISSUE THREAD

**Issue by paulspringett** [shenoudab/active_device#2]
This is the simulator page http://www.opera.com/mini/demo/

It's sending the user agent string "Opera/9.80 (J2ME/MIDP; Opera Mini/5.0.16875/958; U; en) Presto/2.4.15"

Considering it includes "Opera Mini", "Presto" and "J2ME" this seems like it should be considered mobile?

**Comment by shenoudab** [comment]
Opera Simulator, Opera Mini and also Opera Mobile is now considered as Mobile Devices with Brand Opera. applied in the master.

Thanks for your issue sharing.
