### ISSUE TITLE
JSON request from mobile device

### ISSUE THREAD

**Issue by leviathan** [shenoudab/active_device#4]
On my mobile device I'm using JavaScript to fetch some data from a backend server.
The JSON request's format is :json (a.k.a "application/json"). But your :set_mobile_format before_filter ignores this and sets the format to :mobile (a.k.a. "text/html"). 

This causes  a 406 Not Acceptable error in the controller response, when a JSON request comes in with format "JSON" (a.k.a "application/json") but the response comes in format "text/html".

```
respond_to do |format|
  format.json do
    # never gets called because format is set to :mobile by set_mobile_format filter
  end
end
```

Any way to add additional skip_before_filter test?
Or maybe only apply your test if the incoming request format is :html
Or let me specify a list of formats for which the set_mobile_format method should be called.

**Comment by shenoudab** [comment]
Hallo, 

for setting the mobile format to accept json , please check the below
 in the initializers/mime_types.rb set the below
Mime::Type.register_alias "application/json", :mobile
and in the respond_to in your controller add :
 format.mobile { render :json => @{object} }

now any request came as json or mobile will be treated as application/json.
