### ISSUE TITLE
Palm Pre not detected

### ISSUE THREAD

**Issue by leviathan** [shenoudab/active_device#5]
Palm Pre user agent (http://user-agent-string.info/list-of-ua/browser-detail?browser=Palm%20Pre%20web%20browser) seems to go unnoticed as a mobile device.

I guess you're checking for "/Palm/", but checking for "/Pre/" would recognize Palm Pre devices.

**Comment by shenoudab** [comment]
i will going to add Palm and webOS supporting in my next update.

**Comment by leviathan** [comment]
Is there an estimate on when this will happen?
I need this rather sooner than later. So I might go ahead and have to patch it myself.

**Comment by leviathan** [comment]
I will validate if your new version detects Palm Pre. The user agent I'm detecting on my site is: 
    Mozilla/5.0 (webOS/1.4.1; U; de-DE) AppleWebKit/532.2 (KHTML, like Gecko) Version/1.0 Safari/532.2 Pre/1.0

**Comment by leviathan** [comment]
Palm Pre is detected as mobile device. Works perfectly! Thanks you!
