### ISSUE TITLE
Android OS detection?

### ISSUE THREAD

**Issue by leviathan** [shenoudab/active_device#6]
I've checked http://github.com/shenoudab/active_device/blob/master/lib/active_device/os.rb but I can't see any Android OS detection values. Is Android OS detection supported?

**Comment by shenoudab** [comment]
Dear .. 

 for now Android as an OS in User Agents is not supported ...
but if you have set of users agents from Android OS, you can share it 
so can add Android support according these user agents list.

**Comment by leviathan** [comment]
The user agent I'm getting is 
    Mozilla/5.0 (Linux; U; Android 1.5; zh-tw; HTC Magic Build/CUPCAKE) AppleWebKit/528.5+ (KHTML, like Gecko) Version/3.1.2 Mobile Safari/525.20.1

Apparently Android is a Linux flavor, which uses AppleWebKit, but can't the os.rb script additionally detect the Android OS for these user agents. Like:
    when /Android/i               ; :Android
(before Linux detection string)

This is not wrong from a technical point of view and your agent_os helper method would return "Android" instead of "unknown" (as it does right now).

**Comment by shenoudab** [comment]
dear mobilemelting,

  activedevice is planned to add the Android support in our next version. as not just the OS adding will make Android supported by activedevice.

thanks for sharing the user-agent and the issue with us.

**Comment by leviathan** [comment]
Additionally I can confirm the user agents found here: http://www.infinitezest.com/UserAgents/UserAgentResults.aspx?Category=Safari%20Android

**Comment by shenoudab** [comment]
Dear Jörg, 

 kindly, find the new updates for Android enhancement.
