### ISSUE TITLE
Helper methods don't work

### ISSUE THREAD

**Issue by swrobel** [shenoudab/active_device#7]
I get undefined local variable or method `device_brand' after including ActiveDevise. The is_mobile_browser? method works, but the helpers to give the device brand and model don't work.

**Comment by shenoudab** [comment]
Thanks for your interest.

i update active_device for Rails 3 Helpers Support.
you can update your code with active_device master.

**Comment by swrobel** [comment]
Are you submitting a new gem?

**Comment by shenoudab** [comment]
i will the upcoming days ... for now you can use the master 
gem 'active_device', :git => 'git://github.com/shenoudab/active_device.git'

**Comment by swrobel** [comment]
Thanks. I'm still unable to use device_brand or device_model in my controller. I updated my Gemfile, did bundle install and have include ActiveDevice in the controller, but I still get the same error.

**Comment by shenoudab** [comment]
what rails version you are using ?

**Comment by swrobel** [comment]
Sorry, meant to mention that: 3.0.3

**Comment by swrobel** [comment]
Just to be certain I removed the 1.1.0 version gem from my local gems to make sure it is using the git version, did bundle update, and it still isn't finding those helpers. As I mentioned, is_mobile_browser? works but not device_model or device_brand. For example:
    if is_mobile_browser?
      logger.info "Mobile " + device_model + " at " + request.fullpath
Will show the following in my logs if using a mobile browser (and no error with a desktop browser):
    undefined local variable or method `device_model'

**Comment by shenoudab** [comment]
did you add the below line in your Gemfile :
gem 'active_device', :git => 'git://github.com/shenoudab/active_device.git'
and then run "bundle install"

with adding Mobile format : 
Mime::Type.register_alias "text/html", :mobile

as i have test active_device with rails 3.0.3.
please, update me with if any error raised.

**Comment by swrobel** [comment]
Yes, I did everything like that. Here is the exact code from ApplicationController:
    class ApplicationController < ActionController::Base
      include ActiveDevice
      skip_before_filter :set_mobile_format # instead of requiring mobile pages to be .mobile.erb use .html.erb
      before_filter :mobile_redirect # check for mobile browser and redirect to mobile page

```
  def mobile_redirect
    # only redirect to mobile site if mobile browser detected and not already on mobile site
    if is_mobile_browser? && !(request.fullpath+"/").include?("/m/")
      logger.info "Mobile " + device_model + " at " + request.fullpath
      m_path = "/m" + request.fullpath
      Rails.application.routes.recognize_path(m_path, :method => :get)
      redirect_to m_path
    end
  rescue Exception => e
    logger.info e.message
  end
end
```

**Comment by shenoudab** [comment]
hallo, i got that you use device_model in controller and it's working in the views and not included in controller.

if its required by you to use device_model inside controller, its welcome to send us a pull request or it may be included in upcoming versions of active_device.

**Comment by swrobel** [comment]
If it helps anyone else, I just changed my controller's include to:
    include ActiveDevice::Helper
Make sure to apply .to_s to device_model or device_brand if you're sending them to logger because they return symbols.
