### ISSUE TITLE
W3C validator detected as mobile by is_mobile_browser?

### ISSUE THREAD

**Issue by swrobel** [shenoudab/active_device#8]
http://validator.w3.org

**Comment by shenoudab** [comment]
what is the user_agent you using.
as http://validator.w3.org is a webpage not a user agent.
as is_mobile_browser? detect the device not website

**Comment by swrobel** [comment]
Check out these lines of code from browser.rb:
    when /W3C-checklink/i        ; :'W3C-checklink' # Link Checker
    when /W3C_CSS_Validator_JFouffa/i ; :W3C_CSS_Validator_JFouffa # Validator
    when /W3C_Validator/i        ; :W3C_Validator # Validator
The validator pulls up the site in the background and it seems that active_device detects it as mobile because of its user agent and thus my site redirects to the mobile version.

**Comment by shenoudab** [comment]
provide me with your useragent. 
and the steps you do to get that.

**Comment by swrobel** [comment]
My logs show: W3C_Validator/1.1
Just go to http://validator.w3.org and put in your site address and make sure your logs are set to show the user agent that is requesting. The validator calls up the page and checks for valid HTML and it uses the user-agent above, which your gem detects as mobile for some reason due to the matching expressions I referenced earlier.
